export const WORD_DATABASE = [
  // 4 letters
  'amor', 'casa', 'vida', 'tempo', 'água', 'fogo', 'terra', 'vento', 'medo', 'fome',
  'sede', 'sono', 'dor', 'paz', 'luz', 'som', 'cor', 'flor', 'mar', 'céu',
  'sol', 'lua', 'dia', 'noite', 'ano', 'mês', 'hora', 'vez', 'lado', 'parte',
  'lugar', 'modo', 'tipo', 'caso', 'obra', 'ideia', 'meio', 'fim', 'nome', 'face',
  'olho', 'mão', 'pé', 'boca', 'dente', 'unha', 'pelo', 'pele', 'osso', 'alma',
  'ação', 'arte', 'ato', 'base', 'bem', 'bola', 'bolo', 'cama', 'café', 'cão',
  'gato', 'rato', 'pato', 'galo', 'vaca', 'bode', 'urso', 'lobo', 'leão', 'cobra',
  'pato', 'sapo', 'peixe', 'rede', 'sede', 'tema', 'zona', 'auto', 'data', 'erro',
  'fato', 'foto', 'gelo', 'jogo', 'lago', 'loja', 'meta', 'nota', 'ouro', 'pano',
  'roda', 'sala', 'tela', 'vila', 'voto', 'onda', 'unha', 'sede', 'neve', 'neto',

  // 5 letters
  'Brasil', 'mundo', 'gente', 'coisa', 'poder', 'grupo', 'ponto', 'valor', 'forma',
  'força', 'campo', 'ordem', 'fundo', 'linha', 'vista', 'prova', 'porta', 'folha',
  'papel', 'livro', 'escola', 'igreja', 'ponte', 'praia', 'monte', 'pedra', 'ferro',
  'ouro', 'prata', 'verde', 'azul', 'branco', 'preto', 'doce', 'amargo', 'quente',
  'frio', 'seco', 'molhado', 'limpo', 'sujo', 'novo', 'velho', 'grande', 'pequeno',
  'alegre', 'triste', 'bravo', 'calmo', 'forte', 'fraco', 'certo', 'errado', 'cheio',
  'vazio', 'largo', 'estreito', 'alto', 'baixo', 'perto', 'longe', 'dentro', 'fora',
  'acima', 'abaixo', 'antes', 'depois', 'cedo', 'tarde', 'agora', 'então', 'aqui',
  'beber', 'comer', 'dormir', 'andar', 'correr', 'voar', 'nadar', 'dançar', 'cantar',
  'falar', 'ouvir', 'ver', 'sentir', 'pensar', 'saber', 'querer', 'poder', 'dever',
  'terra', 'planta', 'flor', 'árvore', 'folha', 'raiz', 'tronco', 'galho', 'fruto',
  'semente', 'grama', 'mato', 'jardim', 'horta', 'bosque', 'campo', 'fazenda',

  // 6 letters
  'pessoa', 'família', 'amigo', 'inimigo', 'vizinho', 'criança', 'jovem', 'adulto',
  'cidade', 'estado', 'país', 'região', 'centro', 'bairro', 'rua', 'praça',
  'mercado', 'loja', 'banco', 'hotel', 'teatro', 'cinema', 'museu', 'parque',
  'jardim', 'floresta', 'deserto', 'montanha', 'vulcão', 'lago', 'rio', 'oceano',
  'animal', 'planta', 'árvore', 'fruta', 'verdura', 'carne', 'peixe', 'leite',
  'açúcar', 'farinha', 'manteiga', 'queijo', 'ovos', 'pão', 'arroz', 'feijão',
  'batata', 'tomate', 'cebola', 'alho', 'sal', 'pimenta', 'óleo', 'vinagre',
  'cadeira', 'mesa', 'cama', 'sofá', 'armário', 'geladeira', 'fogão', 'forno',
  'pratos', 'copos', 'facas', 'garfos', 'colheres', 'panelas', 'tigelas',
  'espelho', 'quadro', 'relógio', 'lâmpada', 'cortina', 'tapete', 'almofada',
  'cobertor', 'travesseiro', 'lençol', 'toalha', 'sabão', 'xampu', 'escova',
  'remédio', 'médico', 'hospital', 'farmácia', 'enfermeiro', 'dentista',
  'cabelo', 'barba', 'bigode', 'sobrancelha', 'cílios', 'orelha', 'nariz',
  'pescoço', 'ombro', 'braço', 'cotovelo', 'punho', 'dedo', 'peito', 'barriga',
  'costas', 'quadril', 'perna', 'joelho', 'tornozelo', 'calcanhar',

  // 7 letters
  'liberdade', 'saudade', 'alegria', 'tristeza', 'raiva', 'surpresa', 'esperança',
  'educação', 'trabalho', 'dinheiro', 'saúde', 'doença', 'medicina', 'hospital',
  'governo', 'política', 'justiça', 'direito', 'cultura', 'história', 'geografia',
  'ciência', 'tecnologia', 'computador', 'internet', 'telefone', 'televisão',
  'música', 'dança', 'pintura', 'escultura', 'literatura', 'poesia', 'romance',
  'futebol', 'basquete', 'natação', 'corrida', 'caminhada', 'viagem', 'turismo',
  'aviação', 'navegação', 'transporte', 'veículo', 'automóvel', 'bicicleta',
  'motocicleta', 'caminhão', 'ônibus', 'trem', 'avião', 'barco', 'navio',
  'estrada', 'avenida', 'rodovia', 'calçada', 'semáforo', 'estacionamento',
  'gasolina', 'álcool', 'diesel', 'energia', 'eletricidade', 'bateria',
  'máquina', 'ferramenta', 'martelo', 'chave', 'parafuso', 'prego', 'arame',
  'cimento', 'tijolo', 'madeira', 'vidro', 'plástico', 'metal', 'borracha',
  'tecido', 'algodão', 'seda', 'linho', 'nylon', 'poliéster', 'couro',
  'calçado', 'sapato', 'sandália', 'chinelo', 'bota', 'tênis', 'meia',
  'roupa', 'camisa', 'calça', 'vestido', 'saia', 'blusa', 'casaco',
  'jaqueta', 'suéter', 'gravata', 'cinto', 'chapéu', 'boné', 'óculos',

  // 8 letters
  'felicidade', 'amizade', 'saudades', 'carinho', 'paixão', 'casamento', 'divórcio',
  'nascimento', 'batizado', 'formatura', 'aposentadoria', 'funeral', 'cemitério',
  'universidade', 'biblioteca', 'laboratório', 'escritório', 'fábrica', 'construção',
  'agricultura', 'pecuária', 'indústria', 'comércio', 'serviço', 'transporte',
  'comunicação', 'informação', 'conhecimento', 'sabedoria', 'inteligência',
  'criatividade', 'imaginação', 'memória', 'consciência', 'personalidade',
  'caráter', 'temperamento', 'humor', 'paciência', 'tolerância', 'respeito',
  'honestidade', 'sinceridade', 'lealdade', 'fidelidade', 'confiança',
  'responsabilidade', 'disciplina', 'organização', 'planejamento', 'estratégia',
  'liderança', 'chefia', 'administração', 'gerência', 'coordenação',
  'vendedor', 'comprador', 'cliente', 'fornecedor', 'parceiro', 'concorrente',
  'produto', 'mercadoria', 'qualidade', 'quantidade', 'preço', 'desconto',
  'promoção', 'publicidade', 'propaganda', 'marketing', 'vendas',
  'telefonia', 'informática', 'eletrônica', 'mecânica', 'hidráulica',
  'elétrica', 'química', 'física', 'matemática', 'geometria', 'álgebra',
  'aritmética', 'estatística', 'probabilidade', 'lógica', 'filosofia',
  'psicologia', 'sociologia', 'antropologia', 'arqueologia', 'geologia',
  'biologia', 'zoologia', 'botânica', 'ecologia', 'anatomia', 'fisiologia',

  // 9 letters
  'democracia', 'república', 'monarquia', 'ditadura', 'revolução', 'independência',
  'constituição', 'eleição', 'candidato', 'presidente', 'governador', 'prefeito',
  'secretário', 'ministro', 'deputado', 'senador', 'vereador', 'juiz',
  'advogado', 'promotor', 'defensor', 'delegado', 'investigador', 'detetive',
  'professor', 'estudante', 'pesquisador', 'cientista', 'engenheiro', 'arquiteto',
  'médico', 'enfermeiro', 'dentista', 'veterinário', 'farmacêutico', 'psicólogo',
  'terapeuta', 'fisioterapeuta', 'nutricionista', 'educador', 'pedagogo',
  'jornalista', 'repórter', 'apresentador', 'locutor', 'comentarista',
  'escritor', 'romancista', 'poeta', 'dramaturgo', 'roteirista', 'diretor',
  'produtor', 'ator', 'atriz', 'artista', 'pintor', 'escultor', 'desenhista',
  'fotógrafo', 'cinegrafista', 'editor', 'revisor', 'tradutor', 'intérprete',
  'bibliotecário', 'arquivista', 'museólogo', 'curador', 'restaurador',
  'cozinheiro', 'garçom', 'bartender', 'sommelier', 'confeiteiro', 'padeiro',
  'açougueiro', 'peixeiro', 'fruteiro', 'verdureiro', 'quitandeiro',
  'motorista', 'piloto', 'maquinista', 'marinheiro', 'capitão', 'comandante',
  'soldado', 'sargento', 'tenente', 'capitão', 'major', 'coronel', 'general',
  'bombeiro', 'policial', 'guarda', 'vigilante', 'segurança', 'porteiro',
  'zelador', 'faxineiro', 'jardineiro', 'pedreiro', 'carpinteiro', 'eletricista',
  'encanador', 'pintor', 'marceneiro', 'serralheiro', 'soldador', 'mecânico',
  'borracheiro', 'funileiro', 'torneiro', 'fresador', 'operador', 'técnico',

  // 10+ letters
  'desenvolvimento', 'crescimento', 'progresso', 'evolução', 'transformação',
  'modernização', 'globalização', 'urbanização', 'industrialização',
  'democratização', 'descentralização', 'municipalização', 'federalização',
  'nacionalização', 'internacionalização', 'profissionalização',
  'especialização', 'generalização', 'particularização', 'caracterização',
  'personalização', 'individualização', 'coletivização', 'socialização',
  'privatização', 'estatização', 'burocratização', 'tecnologização',
  'informatização', 'digitalização', 'automatização', 'robotização',
  'sustentabilidade', 'responsabilidade', 'biodiversidade', 'multiculturalismo',
  'interdisciplinaridade', 'transdisciplinaridade', 'competitividade',
  'produtividade', 'lucratividade', 'rentabilidade', 'viabilidade',
  'confiabilidade', 'disponibilidade', 'acessibilidade', 'usabilidade',
  'funcionalidade', 'compatibilidade', 'interoperabilidade', 'escalabilidade',
  'flexibilidade', 'adaptabilidade', 'maleabilidade', 'elasticidade',
  'resistência', 'durabilidade', 'estabilidade', 'segurança', 'proteção',
  'prevenção', 'manutenção', 'conservação', 'preservação', 'restauração',
  'recuperação', 'reabilitação', 'revitalização', 'regeneração', 'renovação',
  'inovação', 'criação', 'invenção', 'descoberta', 'exploração', 'investigação',
  'pesquisa', 'experimentação', 'demonstração', 'comprovação', 'verificação',
  'validação', 'confirmação', 'certificação', 'qualificação', 'capacitação',
  'treinamento', 'aperfeiçoamento', 'melhoramento', 'otimização', 'maximização',
  'minimização', 'padronização', 'normatização', 'regulamentação', 'legislação',
  'administração', 'coordenação', 'supervisão', 'fiscalização', 'monitoramento',
  'acompanhamento', 'controle', 'gestão', 'direção', 'liderança', 'comando',
  'organização', 'planejamento', 'programação', 'agendamento', 'cronograma',
  'orçamento', 'financiamento', 'investimento', 'aplicação', 'poupança',
  'economia', 'contabilidade', 'auditoria', 'consultoria', 'assessoria',
  'orientação', 'aconselhamento', 'recomendação', 'sugestão', 'proposta',
  'projeto', 'programa', 'plano', 'estratégia', 'tática', 'metodologia',
  'procedimento', 'protocolo', 'regulamento', 'instrução', 'manual',
  'documentação', 'arquivo', 'registro', 'cadastro', 'banco', 'base',
  'sistema', 'plataforma', 'aplicativo', 'software', 'programa', 'ferramenta',
  'instrumento', 'equipamento', 'aparelho', 'dispositivo', 'mecanismo',
  'componente', 'elemento', 'material', 'substância', 'composto', 'mistura',
  'solução', 'resultado', 'consequência', 'efeito', 'impacto', 'influência',
  'interferência', 'interação', 'comunicação', 'relacionamento', 'convivência',
  'cooperação', 'colaboração', 'participação', 'contribuição', 'envolvimento',
  'engajamento', 'comprometimento', 'dedicação', 'esforço', 'empenho',
  'determinação', 'persistência', 'perseverança', 'continuidade', 'permanência',
  'estabilidade', 'firmeza', 'solidez', 'consistência', 'coerência', 'lógica',
  'racionalidade', 'sensatez', 'prudência', 'sabedoria', 'experiência',
  'conhecimento', 'habilidade', 'competência', 'capacidade', 'aptidão',
  'talento', 'dom', 'vocação', 'inclinação', 'tendência', 'preferência',
  'escolha', 'decisão', 'determinação', 'resolução', 'solução', 'resposta',
  'alternativa', 'opção', 'possibilidade', 'oportunidade', 'chance', 'ocasião',
  'momento', 'instante', 'segundo', 'minuto', 'hora', 'período', 'fase',
  'etapa', 'estágio', 'nível', 'grau', 'categoria', 'classificação', 'tipo',
  'modelo', 'padrão', 'exemplo', 'amostra', 'demonstração', 'ilustração',
  'representação', 'simbolização', 'significação', 'interpretação', 'tradução',
  'explicação', 'esclarecimento', 'elucidação', 'compreensão', 'entendimento',
  'percepção', 'observação', 'contemplação', 'admiração', 'apreciação',
  'valorização', 'reconhecimento', 'agradecimento', 'gratidão', 'satisfação',
  'contentamento', 'alegria', 'felicidade', 'prazer', 'diversão', 'entretenimento',
  'distração', 'relaxamento', 'descanso', 'repouso', 'tranquilidade', 'serenidade',
  'calma', 'paz', 'harmonia', 'equilíbrio', 'estabilidade', 'ordem', 'disciplina',
  'organização', 'estrutura', 'arquitetura', 'construção', 'edificação',
  'estabelecimento', 'instituição', 'organismo', 'entidade', 'associação',
  'sociedade', 'comunidade', 'coletividade', 'população', 'habitantes',
  'moradores', 'residentes', 'cidadãos', 'brasileiros', 'americanos', 'europeus',
  'asiáticos', 'africanos', 'oceânicos', 'continentais', 'planetários', 'mundiais',
  'internacionais', 'nacionais', 'regionais', 'locais', 'municipais', 'estaduais',
  'federais', 'governamentais', 'administrativos', 'burocráticos', 'oficiais',
  'formais', 'informais', 'pessoais', 'profissionais', 'comerciais', 'industriais',
  'agrícolas', 'tecnológicos', 'científicos', 'educacionais', 'culturais',
  'artísticos', 'esportivos', 'recreativos', 'turísticos', 'gastronômicos',
  'culinários', 'alimentares', 'nutricionais', 'medicinais', 'terapêuticos',
  'preventivos', 'curativos', 'paliativos', 'emergenciais', 'urgentes',
  'importantes', 'essenciais', 'fundamentais', 'básicos', 'elementares',
  'primários', 'secundários', 'terciários', 'quaternários', 'superiores',
  'avançados', 'sofisticados', 'complexos', 'complicados', 'difíceis',
  'desafiadores', 'interessantes', 'fascinantes', 'impressionantes',
  'extraordinários', 'maravilhosos', 'fantásticos', 'incríveis', 'surpreendentes'
];
